### ISSUE TITLE
Socket Hang Up Issue [Long Polling]

### ISSUE THREAD

**Issue by rbaid1221** [cometd/cometd-nodejs-client#12]
When making the cometd initial handshake and connection, everything works perfectly. After about 2 connection requests, however, it gives a socket hang up issue.

Any ideas?

{ id: '5',
successful: false,
channel: '/meta/connect',
failure:
{ reason: 'socket hang up',
exception: undefined,
httpCode: 0,
connectionType: 'long-polling',
transport:
{ status: 0,
statusText: 'socket hang up',
readyState: 4,
responseText: '',
open: [Function],
setRequestHeader: [Function],
send: [Function],
abort: [Function],
_config: [Function],
context: undefined,
withCredentials: true,
onload: [Function],
onerror: [Function] },
message:
{ id: '5',
channel: '/meta/connect',
connectionType: 'long-polling',
clientId: '----deleted' } } }

**Comment by sbordet** [comment]
Too little information to understand what's going on.

Please [enable DEBUG logging](https://docs.cometd.org/current/reference/#_troubleshooting_logging_javascript) in CometD and attach the logs to this issue.

What server are you using?
What is the CometD timeout, and what is the server idle timeout?

**Comment by sbordet** [comment]
No further activity, closing.
