### ISSUE TITLE
New cookies sent overwrite ones set in configuration

### ISSUE THREAD

**Issue by leenelc** [cometd/cometd-nodejs-client#13]
Whenever the cometd server sets the bayeux browser cookie on handshake, the original cookie set in  `cometd.configure({requestHeaders:{}})` gets overwritten...
Is there a way I can change this?

**Comment by sbordet** [comment]
Can you please detail?
What exact cookie do you set in the `requestHeaders`, what other cookies are involved, what you see on the server side and what instead you would like to happen.

**Comment by leenelc** [comment]
When configuring the cometd client using, 
cometd.configure({
                url: 'http://localhost:5001',
                requestHeaders: {"cookie": "mycookie=cookie"}
            });
I set a cookie using request headers... 
However, upon establishing the handshake, the cometDServer sets the BAYEUX_BROWSER cookie.
I want both cookies to remain in the subsequent requests sent to the cometDServer.

**Comment by sbordet** [comment]
@leenelc are you able to try the new code and see if it fixed the issue for you?
