### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by thelazyrk** [cometd/cometd-nodejs-client#19]
I'm trying to use with the version 1.0.3 with cometd@3.1.10 I get the error 
```
ReferenceError: window is not defined
at new CometD (~/node_modules/cometd/cometd.js:3303:9)
```

Usage: 

```
require('cometd-nodejs-client').adapt()
const lib = require('cometd')
const TimeStampExtension = require('cometd/TimeStampExtension')
const cometd = new lib.CometD()
```
I see a couple of other issues where window object is not present but they look like different problems.

**Comment by sbordet** [comment]
Please update to the latest `cometd` version.
