### ISSUE TITLE
2.0 release

### ISSUE THREAD

**Issue by XuluWarrior** [cometd/cometd-nodejs-client#22]
The recent changes to support the websocket transport is very useful (at least to me) but currently you need to install the 2.0 beta from npm.

Do you plan on making a 2.0 release?  Or is there something blocking?

**Comment by sbordet** [comment]
I plan to make a release next week, after fixing also #23. Thanks!

**Comment by sbordet** [comment]
@XuluWarrior I decided to name the release with WebSocket support 1.2.0 rather than 2.0.0, since it's a backwards compatible change.
It's published.
