### ISSUE TITLE
TypeError: HttpsProxyAgent is not a constructor

### ISSUE THREAD

**Issue by nicob-29** [cometd/cometd-nodejs-client#29]
Hi 
version 1.3.0 
If a proxy is defined and includes contains HTTPS url. Handshake failed because it is not possible to instantiate HttpsProxyAgent.

If I replace
``
return _secure(serverURI) ? new HttpsProxyAgent(agentOpts) : new HttpcProxyAgent(agentOpts);
``
by
``
return _secure(serverURI) ? new HttpsProxyAgent.HttpsProxyAgent(agentOpts) : new HttpcProxyAgent(agentOpts);
``
No exception is raised

![image](https://github.com/cometd/cometd-nodejs-client/assets/56296287/e0c1334c-cd54-481b-9208-c594ccde6675)
Image shows the current implmentation doesn't  consider new HttpsProxyAgent(agentOpts) has constructor

**Comment by sbordet** [comment]
Thanks for reporting this, a fix in underway.
