### ISSUE TITLE
Cookies not being saved correctly

### ISSUE THREAD

**Issue by marshalllamb** [cometd/cometd-nodejs-client#7]
salesforce.com sets 3 cookies on responses to handshakes and subscribes, but the logic in the XMLHttpRequest send() function is preserving cookies as individual array values instead of collapsing them into a single Cookie header. I modified the logic as follows, and it works:

        for (var i = 0; i < _cookies.length; ++i) {
            _config.headers['Cookie'] = _config.headers['Cookie'] + _cookies[i] + ';';
        }

**Comment by sbordet** [comment]
What version are you using ? This is supposed to be fixed in #2.

**Comment by marshalllamb** [comment]
1.0.0-BETA0

**Comment by sbordet** [comment]
Please install the version at tag `beta`, should be `1.0.0-BETA3`.

**Comment by marshalllamb** [comment]
Thanks. That works.

Would you also add support for https? I doctored the require to be for 'https' instead of 'http' since the Bayeux server I'm connecting to only supports https. I can open another Issue if you want.

**Comment by sbordet** [comment]
The `https` issue is already resolved by #6. It's not been published to NPM yet, though.

**Comment by sbordet** [comment]
`https` support landed in 1.0.0-BETA4.
